log:
  level: debug
  console:
    encoding: json

session:
  cookie_name: webauthn
  secure: yes
  domain: localhost

# listen_address: "0.0.0.0:8080"
listen_address: "http://localhost:3001"
# external_url: https://auth.example.com
external_url: http://localhost:8000

display_name: Webauthn
conveyance_preference: indirect
authenticator_attachment: cross-platform
user_verification_requirement: preferred